### ISSUE TITLE
FrontEnd - Home Page - The Search functionality is not working

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#1]
The Search functionality is not working

![image](https://user-images.githubusercontent.com/49487834/55909482-7972a500-5bdc-11e9-921c-4c9595bdd820.png)

**Comment by nadagouda** [comment]
Fixed.

**Comment by NourhanYoussef** [comment]
The search functionality is not working from myside as the access from strapi is not working and @M-Abuelatta is checking.

**Comment by norangamal** [comment]
The issue is still exists.
When you search with word النوع for ex it gave me a blank page as below:
￼

**Comment by norangamal** [comment]
![New Note](https://user-images.githubusercontent.com/51783494/59589130-8edae280-90e9-11e9-893b-100c0209343c.jpeg)

**Comment by abdelazizelsaman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FrontEnd - In مكتبة الجهاز - The search is not working #38](https://trello.com/c/cQjpm5ZO/18-frontend-in-%D9%85%D9%83%D8%AA%D8%A8%D8%A9-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-the-search-is-not-working-38)

**Comment by abdelazizelsaman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FrontEnd - Home Page - The Search functionality is not working #1](https://trello.com/c/3C8rEYon/19-frontend-home-page-the-search-functionality-is-not-working-1)

**Comment by Omar-Handouk** [comment]
Fixed in pull request #79, please retest

**Comment by OmarReda** [comment]
Need to be closed the issue is solved.
