### ISSUE TITLE
FrontEnd/Backend - Competitions - Awards field is not mapped in the portal

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#33]
In Competitions - "Awards" field is not mapped in the portal

Backend:
![image](https://user-images.githubusercontent.com/49487834/56095567-8e9e4b00-5ede-11e9-8845-7d8012a81b97.png)

Portal:
![image](https://user-images.githubusercontent.com/49487834/56095580-a1b11b00-5ede-11e9-8283-3b0bfc7ac70c.png)

**Comment by nadagouda** [comment]
@NourhanYoussef This is fixed, you'll see it mapped in competition details page if the award is added in backend and in competition of the month page

**Comment by NourhanYoussef** [comment]
@nadagouda Failed Verification.
Still not displayed although it is added in the backend.
Please check the below screenshots
![image](https://user-images.githubusercontent.com/49487834/56662090-76c78380-66a3-11e9-8711-1869d16b4a40.png)

![image](https://user-images.githubusercontent.com/49487834/56662114-8b0b8080-66a3-11e9-9ac3-64396f06fa8a.png)

**Comment by NourhanYoussef** [comment]
Fixed and Passed Verification.
